openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
servers:
  - url: http://localhost:7777/api
tags:
  - name: Item
paths:
  /item:
    $ref: './resources/item.yaml#/ItemPath'
  /item/{id}:
    $ref: './resources/item.yaml#/UserPathWithID'
  /user:
    $ref: './resources/user.yaml#/UserPath'

components:
  schemas:
    Item:
      $ref: './schemas/item_schema.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

