openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
servers:
  - url: http://localhost:7777/api
tags:
  - name: Item
paths:
  /item:
    $ref: './resources/item.yaml#/ItemPath'
  /user/{id}:
    $ref: './resources/item.yaml#/UserPathWithID'

components:
  schemas:
    Item:
      $ref: './schemas/item_schema.yaml'
#  securitySchemes:
#    BearerAuth:
#      $ref: './schemas/security_schema.yaml'